### ISSUE TITLE
getting ENOENT error

### ISSUE THREAD

**Issue by DmitryEfimenko** [timoxley/cruft#9]
Wanted to check this out.
Running `cruft clear` gives me this:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files\nodejs\node_modules\cruft\bin/cruft-clear ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:140:18)
    at node.js:1001:3
```

In case it makes difference, I'm on Windows 10.
Any help is appreciated.

**Comment by mattklein999** [comment]
+1

**Comment by burner03** [comment]
Getting this as well. Seems like a lot of node-apps are not working as intended on windows.
